### ISSUE TITLE
Not having success

### ISSUE THREAD

**Issue by ckonkel** [monetate/ectou-export#3]
If this can do what I think you say it does ...it will be a godsend!

On a Mac
Connected to VPC...
All dependencies installed...

This is the result ... any insight?

A-CKONKEL-MBPR:ectou-export-master ckonkel$ ./export.py --ami-name amzn-ami-hvm-2015.09.1.x86_64-gp2
get ec2.Image(id='ami-60b6c60a')
create ec2.KeyPair(name='ectou-export-1eb1f249-cb31-48fa-9f4a-966615c16c13')
create ec2.SecurityGroup(id='sg-8e7e6fe4')
exception An error occurred (InvalidParameter) when calling the RunInstances operation: The AssociatePublicIpAddress parameter is only supported for VPC launches.
delete ec2.SecurityGroup(id='sg-8e7e6fe4')
delete ec2.KeyPair(name='ectou-export-1eb1f249-cb31-48fa-9f4a-966615c16c13')
Traceback (most recent call last):
  File "./export.py", line 326, in <module>
    main()
  File "./export.py", line 292, in main
    AssociatePublicIpAddress=True,
  File "/Library/Python/2.7/site-packages/boto3/resources/factory.py", line 456, in do_action
    response = action(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 301, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 398, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameter) when calling the RunInstances operation: The AssociatePublicIpAddress parameter is only supported for VPC launches.
A-CKONKEL-MBPR:ectou-export-master ckonkel$ ./export.py --ami-name amzn-ami-hvm-2015.09.1.x86_64-gp2
get ec2.Image(id='ami-60b6c60a')
create ec2.KeyPair(name='ectou-export-94984eb4-8a6f-4718-b2c6-379b9b36db26')
create ec2.SecurityGroup(id='sg-087c6d62')
exception An error occurred (InvalidParameter) when calling the RunInstances operation: The AssociatePublicIpAddress parameter is only supported for VPC launches.
delete ec2.SecurityGroup(id='sg-087c6d62')
delete ec2.KeyPair(name='ectou-export-94984eb4-8a6f-4718-b2c6-379b9b36db26')
Traceback (most recent call last):
  File "./export.py", line 326, in <module>
    main()
  File "./export.py", line 292, in main
    AssociatePublicIpAddress=True,
  File "/Library/Python/2.7/site-packages/boto3/resources/factory.py", line 456, in do_action
    response = action(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 301, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 398, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameter) when calling the RunInstances operation: The AssociatePublicIpAddress parameter is only supported for VPC launches.

**Comment by jjpersch** [comment]
Try using the --vpc-name or --vpc-id arguments.

If those are not specified, it will assume the account has a default VPC, which will not be the case for any account that supports Classic instances.
